biocypher:
  strict_mode: true
  schema_config_path: config/extended_target_disease_schema_config.yaml

neo4j:
  database_name: test
  delimiter: '\t'
  array_delimiter: '|'
  skip_bad_relationships: true